### ISSUE TITLE
App crash (WindowManager)

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#139]
In Android 8 emulator.

```
05-01 12:48:55.427  4232  4232 E WindowManager: 
05-01 12:48:55.427  4232  4232 E WindowManager: android.view.WindowLeaked: Activity nl.eduvpn.app.MainActivity has leaked window DecorView@22ddd3a[Just a sec] that was originally added here
05-01 12:48:55.427  4232  4232 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at android.app.Dialog.show(Dialog.java:330)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at android.app.ProgressDialog.show(ProgressDialog.java:185)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at android.app.ProgressDialog.show(ProgressDialog.java:159)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at nl.eduvpn.app.fragment.HomeFragment._downloadKeyPairIfNeeded(HomeFragment.java:522)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at nl.eduvpn.app.fragment.HomeFragment._onItemClicked(HomeFragment.java:243)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at nl.eduvpn.app.fragment.HomeFragment.access$000(HomeFragment.java:85)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at nl.eduvpn.app.fragment.HomeFragment$1.onItemClicked(HomeFragment.java:175)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at nl.eduvpn.app.utils.ItemClickSupport$1.onClick(ItemClickSupport.java:39)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at android.view.View.performClick(View.java:6294)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at android.view.View$PerformClick.run(View.java:24770)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:790)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at android.os.Looper.loop(Looper.java:164)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-01 12:48:55.427  4232  4232 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by dzolnai** [comment]
This is not a crash log, just an error, which is a side effect of the crash.
The crash stack trace would be before this error in the logs.
Please update this issue if it happens again.

**Comment by fkooman** [comment]
should that be visible also when filtering `*:E` with `adb logcal`?

**Comment by dzolnai** [comment]
Yes, above this error

**Comment by dzolnai** [comment]
Closing this because of missing info, please reopen if it happens again.
