### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by ghost** [eduvpn/android#165]
```
05-14 15:48:20.074 11792 12153 E AndroidRuntime: FATAL EXCEPTION: Thread-7
05-14 15:48:20.074 11792 12153 E AndroidRuntime: Process: nl.eduvpn.app, PID: 11792
05-14 15:48:20.074 11792 12153 E AndroidRuntime: java.lang.RuntimeException: Cannot find any execulte for this device's ABIs [Ljava.lang.String;@f6f9ae9
05-14 15:48:20.074 11792 12153 E AndroidRuntime: 	at de.blinkt.openvpn.core.VPNLaunchHelper.writeMiniVPN(VPNLaunchHelper.java:51)
05-14 15:48:20.074 11792 12153 E AndroidRuntime: 	at de.blinkt.openvpn.core.VPNLaunchHelper.buildOpenvpnArgv(VPNLaunchHelper.java:76)
05-14 15:48:20.074 11792 12153 E AndroidRuntime: 	at de.blinkt.openvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:566)
05-14 15:48:20.074 11792 12153 E AndroidRuntime: 	at de.blinkt.openvpn.core.OpenVPNService.access$200(OpenVPNService.java:62)
05-14 15:48:20.074 11792 12153 E AndroidRuntime: 	at de.blinkt.openvpn.core.OpenVPNService$3.run(OpenVPNService.java:536)
05-14 15:48:20.074 11792 12153 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by fkooman** [comment]
- reboot after upgrade still works
- adding a new provider after reboot also works

**Comment by fkooman** [comment]
```
apkanalyzer apk compare A B
```

https://gist.github.com/fkooman/f8c8cd0a6db0c05cf8051919892b8ffe

**Comment by fkooman** [comment]
Things to investigate:

- [ ] try with `gradlew` as freshly generated by android studio for new projects and see if any other "boilerplate" files are different...

**Comment by fkooman** [comment]
`ovpnassets` ssems to be not copied to the assets dir when we use gradle with eduVPN, but they are apparently added when using studio.

**Comment by fkooman** [comment]
But don't understand why upgrades would work with missing assets.

**Comment by fkooman** [comment]
the ics-openvpn/main/build.gradle misses some stuff, tried to add it from the official ics-openvpn, but it doesn't work.

```

* What went wrong:
Execution failed for task ':ics-openvpn-main:externalNativeBuildNoovpn3Release'.
> java.io.FileNotFoundException: /home/fkooman/StudioProjects/eduvpn-android/ics-openvpn/main/.externalNativeBuild/cmake/noovpn3Release/armeabi-v7a/android_gradle_build.json (No such file or directory)

```
