### ISSUE TITLE
gradle snafus

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#242]
And again...

```
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variant.getExternalNativeBuildTasks()' is obsolete and has been replaced with 'variant.getExternalNativeBuildProviders()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getExternalNativeBuildTasks(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Injecting the input artifact of a transform as a File has been deprecated. This is scheduled to be removed in Gradle 6.0. Declare the input artifact as Provider<FileSystemLocation> instead.
```

**Comment by dzolnai** [comment]
Fixed

**Comment by fkooman** [comment]
```
> Configure project :app
The BuildListener.buildStarted(Gradle) method has been deprecated. This is scheduled to be removed in Gradle 7.0. Consult the upgrading guide for further information: https://docs.gradle.org/6.2.2/userguide/upgrading_version_5.html#apis_buildlistener_buildstarted_and_gradle_buildstarted_have_been_deprecated
        at org.gradle.invocation.DefaultGradle.nagBuildStartedDeprecationIfOverriden(DefaultGradle.java:410)
```

**Comment by fkooman** [comment]
Let's keep this as a Gradle problems tracker issue

**Comment by fkooman** [comment]
```
> Task :app:checkBasicReleaseManifest
Property 'manifest' has @Input annotation used on property of type 'File'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.2.2/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
        at org.gradle.internal.service.scopes.GlobalScopeServices.lambda$createValidationWarningReporter$1(GlobalScopeServices.java:316)
```

**Comment by fkooman** [comment]
```
> Task :app:dataBindingExportBuildInfoBasicRelease
Type 'DataBindingExportBuildInfoTask': field 'xmlProcessor' without corresponding getter has been annotated with @Internal. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.2.2/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
        at org.gradle.internal.service.scopes.GlobalScopeServices.lambda$createValidationWarningReporter$1(GlobalScopeServices.java:316)
```

**Comment by fkooman** [comment]
```
> Task :ics-openvpn-main:packageUiReleaseResources
Property 'resourcesComputer' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.2.2/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
        at org.gradle.internal.service.scopes.GlobalScopeServices.lambda$createValidationWarningReporter$1(GlobalScopeServices.java:316)
```

**Comment by fkooman** [comment]
```
> Task :app:dataBindingExportFeaturePackageIdsBasicRelease
Property 'featureDeclarations' is declared without normalization specified. Properties of cacheable work must declare their normalization via @PathSensitive, @Classpath or @CompileClasspath. Defaulting to PathSensitivity.ABSOLUTE. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.2.2/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
        at org.gradle.internal.service.scopes.GlobalScopeServices.lambda$createValidationWarningReporter$1(GlobalScopeServices.java:316)
```

**Comment by fkooman** [comment]
```
Property 'workers' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.2.2/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
```

**Comment by fkooman** [comment]
Okay, and 50 more...

**Comment by dzolnai** [comment]
These are all warning from the Android plugins, such as databinding or lint.
So we can't fix these.
