### ISSUE TITLE
crash on fetching profiles

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#65]
maybe related to #59 
```
11-17 19:15:27.264  4510  4510 E nl.eduvpn.app.fragment.HomeFragment: Error fetching profile list: java.net.ConnectException: failed to connect to labrat.eduvpn.nl/2001:610:188:418:145:0:6:34 (port 443) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
11-17 19:15:27.274  4510  4510 D AndroidRuntime: Shutting down VM
11-17 19:15:27.294  4510  4510 E AndroidRuntime: FATAL EXCEPTION: main
11-17 19:15:27.294  4510  4510 E AndroidRuntime: Process: nl.eduvpn.app, PID: 4510
11-17 19:15:27.294  4510  4510 E AndroidRuntime: Theme: themes:{}
11-17 19:15:27.294  4510  4510 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(int)' on a null object reference
11-17 19:15:27.294  4510  4510 E AndroidRuntime: 	at nl.eduvpn.app.fragment.HomeFragment._checkLoadingFinished(HomeFragment.java:334)
11-17 19:15:27.294  4510  4510 E AndroidRuntime: 	at nl.eduvpn.app.fragment.HomeFragment.access$400(HomeFragment.java:79)
11-17 19:15:27.294  4510  4510 E AndroidRuntime: 	at nl.eduvpn.app.fragment.HomeFragment$4.onError(HomeFragment.java:300)
11-17 19:15:27.294  4510  4510 E AndroidRuntime: 	at nl.eduvpn.app.service.APIService$1.onPostExecute(APIService.java:140)
11-17 19:15:27.294  4510  4510 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:651)
11-17 19:15:27.294  4510  4510 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
11-17 19:15:27.294  4510  4510 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
11-17 19:15:27.294  4510  4510 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-17 19:15:27.294  4510  4510 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
11-17 19:15:27.294  4510  4510 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
11-17 19:15:27.294  4510  4510 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-17 19:15:27.294  4510  4510 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-17 19:15:27.294  4510  4510 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-17 19:15:27.339  2354  5408 W ActivityManager:   Force finishing activity nl.eduvpn.app/.MainActivity
```

**Comment by fkooman** [comment]
```
11-17 19:19:02.624  4753  4753 D AndroidRuntime: Shutting down VM
11-17 19:19:02.624  4753  4753 E AndroidRuntime: FATAL EXCEPTION: main
11-17 19:19:02.624  4753  4753 E AndroidRuntime: Process: nl.eduvpn.app, PID: 4753
11-17 19:19:02.624  4753  4753 E AndroidRuntime: Theme: themes:{}
11-17 19:19:02.624  4753  4753 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{nl.eduvpn.app/nl.eduvpn.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String de.blinkt.openvpn.core.OpenVPNService.getLastLocalIpV4Address()' on a null object reference
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String de.blinkt.openvpn.core.OpenVPNService.getLastLocalIpV4Address()' on a null object reference
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at nl.eduvpn.app.service.VPNService.updateState(VPNService.java:252)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at de.blinkt.openvpn.core.VpnStatus.addStateListener(VpnStatus.java:253)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at nl.eduvpn.app.service.VPNService.onCreate(VPNService.java:114)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at nl.eduvpn.app.MainActivity.onCreate(MainActivity.java:62)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6251)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
11-17 19:19:02.624  4753  4753 E AndroidRuntime: 	... 9 more
11-17 19:19:02.834  2354  5408 W ActivityManager:   Force finishing activity nl.eduvpn.app/.MainActivity
```

**Comment by dzolnai** [comment]
Sorry for the crash, fixed.
